trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
# 1) Ensure .NET 8 SDK is on the agent
- task: UseDotNet@2
  displayName: 'Install .NET 8 SDK'
  inputs:
    packageType: 'sdk'
    version: '8.x'

# 2) Restore / Build / Test using the .NET SDK tasks
- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: 'MutationTesting.sln'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: 'MutationTesting.sln'
    arguments: '--configuration $(buildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    projects: 'MutationTesting.Tests/MutationTesting.Tests.csproj'
    arguments: '--configuration $(buildConfiguration) --no-build'

# 3) Make Stryker available (reads .config/dotnet-tools.json)
- script: dotnet tool restore
  displayName: 'Restore dotnet tools (coverlet, stryker)'

# 4) Run Stryker from the TEST PROJECT folder
- script: dotnet stryker
  workingDirectory: $(Build.SourcesDirectory)/MutationTesting.Tests
  displayName: 'Run Stryker HTML'

# 5) Publish the mutation test report
- task: PublishMutationReport@2
  displayName: 'Publish Mutation Test Report'
  inputs:
    reportPattern: '**/mutation-report.html'