trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
# Ensure .NET 8 SDK is on the agent
- task: UseDotNet@2
  displayName: 'Install .NET 8 SDK'
  inputs:
    packageType: 'sdk'
    version: '8.x'

# Restore / Build / Test using the .NET SDK tasks
- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: 'MutationTesting.sln'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: 'MutationTesting.sln'
    arguments: '--configuration $(buildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    projects: 'MutationTesting.Tests/MutationTesting.Tests.csproj'
    arguments: '--configuration $(buildConfiguration) --no-build'

# Make Stryker available (reads .config/dotnet-tools.json)
- script: dotnet tool restore
  displayName: 'Restore dotnet tools (coverlet, stryker)'

# Run Stryker from the TEST PROJECT folder
- script: dotnet stryker
  workingDirectory: $(Build.SourcesDirectory)/MutationTesting.Tests
  displayName: 'Run Stryker (HTML + Dashboard)'
  env:
    STRYKER_DASHBOARD_API_KEY: $(STRYKER_DASHBOARD_API_KEY)

# List the tree so we can see the exact folder in logs
- pwsh: |
    Get-ChildItem -Recurse "$(Build.SourcesDirectory)/MutationTesting.Tests/StrykerOutput" | Select-Object FullName
  displayName: 'List StrykerOutput tree'

# Copy all report files to a known staging folder
- task: CopyFiles@2
  displayName: 'Stage Stryker HTML report'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/MutationTesting.Tests'
    Contents: 'StrykerOutput/**/reports/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/stryker-report'

# Publish the HTML mutation report as an artifact
- task: PublishBuildArtifacts@1
  displayName: 'Publish Stryker HTML report'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/stryker-report'
    ArtifactName: 'stryker-report'